apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - port: 80
      targetPort: 80
    {{- if .Values.ingress.tls }}
    - port: 443
      targetPort: 443
    {{- end }}
  selector:
    app: {{ .Release.Name }}
